sqlite_config_version: 0


# (OPTIONAL | Default: 10) integer value. Defines the connection pool size to SQLite.
# Please see https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
# sqlite_connection_pool_size:


# (COMPULSORY) string value. The file path to the database folder to store SuperTokens related data.
# sqlite_database_folder_location:


# (OPTIONAL | Default: "auth_session") string value. The database name to store SuperTokens related data.
# sqlite_database_name:


# (OPTIONAL | Default: "key_value") string value. Specify the name of the table that will store secret keys
# and app info necessary for the functioning sessions.
# sqlite_key_value_table_name:


# (OPTIONAL | Default: "session_info") string value. Specify the name of the table that will store the
# session info for users.
# sqlite_session_info_table_name:


# (OPTIONAL | Default: "past_tokens") string name. Specify the name of the table that will store old tokens.
# This table will only be used if your licenseKey has expired.
# sqlite_past_tokens_table_name:
