version: 2
jobs:
  test:
    docker:
      - image: rishabhpoddar/supertokens_postgresql_plugin_test
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9a:c7:60:f2:1f:b9:da:55:dd:10:a5:05:0d:9b:9b:da"
      - checkout
      - run:
          name: running tests
          command: (cd .circleci/ && ./doTests.sh)

workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/